# Generated by Django 2.1.1 on 2018-09-12 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('db port', models.CharField(default='3306', max_length=5)),
                ('db user', models.CharField(max_length=20)),
                ('db user password', models.CharField(default='', max_length=20)),
                ('charset', models.CharField(default='utf8', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MessageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
