# Generated by Django 2.1.1 on 2018-09-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0002_auto_20180912_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='name',
            field=models.CharField(default='some database', max_length=50),
        ),
        migrations.AddField(
            model_name='messageconfig',
            name='current_billing_db',
            field=models.ManyToManyField(related_name='cur_bil_db', to='sms_interface.DatabaseConfig'),
        ),
        migrations.AddField(
            model_name='messageconfig',
            name='current_turbosms_db',
            field=models.ManyToManyField(related_name='cur_tsms_db', to='sms_interface.DatabaseConfig'),
        ),
    ]
