# Generated by Django 2.1.1 on 2018-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0004_databaseconfig_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageconfig',
            name='name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
