# Generated by Django 2.1.1 on 2018-09-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0006_auto_20180913_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseconfig',
            old_name='db user password',
            new_name='db_password',
        ),
        migrations.RenameField(
            model_name='databaseconfig',
            old_name='db user',
            new_name='db_user',
        ),
        migrations.RenameField(
            model_name='databaseconfig',
            old_name='db port',
            new_name='port',
        ),
    ]
