# Generated by Django 2.1.1 on 2018-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0007_auto_20180913_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageconfig',
            name='default_message',
            field=models.CharField(default="Popovnit Bud\\'laska vash rahunok #<l> na <d> grn, shob uniknuti vidkluchennia posluh u nastupnomu misyaci.", max_length=150),
        ),
    ]
