# Generated by Django 2.1.1 on 2018-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0011_auto_20180913_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageconfig',
            name='current_billing_db',
        ),
        migrations.AddField(
            model_name='messageconfig',
            name='current_billing_db',
            field=models.ManyToManyField(related_name='cur_bil_db', to='sms_interface.DatabaseConfig'),
        ),
        migrations.RemoveField(
            model_name='messageconfig',
            name='current_turbosms_db',
        ),
        migrations.AddField(
            model_name='messageconfig',
            name='current_turbosms_db',
            field=models.ManyToManyField(related_name='cur_tsms_db', to='sms_interface.DatabaseConfig'),
        ),
    ]
