# Generated by Django 2.1.1 on 2018-09-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0012_auto_20180913_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageconfig',
            name='current_billing_db',
        ),
        migrations.RemoveField(
            model_name='messageconfig',
            name='current_turbosms_db',
        ),
        migrations.AddField(
            model_name='messageconfig',
            name='db_from',
            field=models.ManyToManyField(related_name='MessageConfig_db_from', to='sms_interface.DatabaseConfig'),
        ),
        migrations.AddField(
            model_name='messageconfig',
            name='db_to',
            field=models.ManyToManyField(related_name='MessageConfig_db_to', to='sms_interface.DatabaseConfig'),
        ),
    ]
