# Generated by Django 2.1.1 on 2018-09-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0015_auto_20180914_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseconfig',
            old_name='charset',
            new_name='db_charset',
        ),
    ]
