# Generated by Django 2.1.1 on 2018-09-15 20:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('sms_interface', '0016_auto_20180914_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='config_name',
            field=models.CharField(default='some config name', max_length=50, verbose_name='Название конфига'),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='db_charset',
            field=models.CharField(blank=True, default='utf8', max_length=10, verbose_name='Кодировка БД'),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='db_password',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Пароль пользователя БД'),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='db_user',
            field=models.CharField(max_length=20, verbose_name='Пользователь БД'),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='host',
            field=models.CharField(max_length=50, verbose_name='Хост БД'),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='name',
            field=models.CharField(default='some database', max_length=50, verbose_name='Имя БД'),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='port',
            field=models.CharField(default='3306', max_length=5, verbose_name='Порт БД'),
        ),
        migrations.AlterField(
            model_name='messageconfig',
            name='db_from',
            field=models.ManyToManyField(blank=True, related_name='messageconfig_db_from', to='sms_interface.DatabaseConfig', verbose_name='База откуда'),
        ),
        migrations.AlterField(
            model_name='messageconfig',
            name='db_to',
            field=models.ManyToManyField(blank=True, related_name='messageconfig_db_to', to='sms_interface.DatabaseConfig', verbose_name='База куда'),
        ),
        migrations.AlterField(
            model_name='messageconfig',
            name='default_message',
            field=models.CharField(default="Popovnit Bud\\'laska vash rahunok #<l> na <d> grn, shob uniknuti vidkluchennia posluh u nastupnomu misyaci.", max_length=150, verbose_name='Стандартное сообщение'),
        ),
        migrations.AlterField(
            model_name='messageconfig',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='messageconfig',
            name='name',
            field=models.CharField(default='default', max_length=50, verbose_name='Название конфигурации'),
        ),
    ]
